name: micro_core_http
description: This package is a wrapper of the http package with a handful of features outside the box.
version: 0.0.2
repository: https://github.com/JotaPe-Tecnologia/micro-core-http
issue_tracker: https://github.com/JotaPe-Tecnologia/micro-core-http/issues
homepage: https://www.jotapetecnologia.com.br/flutter/packages/micro_core_http

environment:
  sdk: ^3.2.3

dependencies:
  http: ^1.1.2
  http_parser: ^4.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  coverage: ^1.7.2
  mocktail: ^1.0.2
